void rumble_controller();
void print_stats_controller(bool pto);
void charge_catapult();
void shoot_catapult();
void move_catapult(int degrees);
void set_intake_volts(int volts);
void spin_intake_for(float dist);
void pto_toggle(bool toggle);
void set_pto_volts(int volts);
void pto_control();